[theme]
base="light"                  
primaryColor="#DE7356"        
backgroundColor="#141414"     
secondaryBackgroundColor="#57554eff" 
textColor="#EFEEE5"           
font="Space Mono"        
borderColor="#7a776dff"