[theme]
base="dark"                  
primaryColor="#85BF8A"        
backgroundColor="#1B241F"     
secondaryBackgroundColor="#232D27" 
textColor="#f0f0f0"           
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap, sans-serif"    
borderColor="#c1c1c1ff"